### PR TITLE
Dockerfile revamp

### PR DESCRIPTION
**Pull request by FlyinPancake**
I've been using this repo as a base for my work and personal projects alike. I've made quite a lot of changes, so This might be rejected, and that is fine as well. 

Le changes:

### Switch away from the node / TS image in favour of the base [image from mcr](https://github.com/devcontainers/images/tree/main/src/base-debian) 

This just makes sense, as I don't think node has to be bundled with embedded development.

### Rename and restructure `Containerfile` (`Dockerfile`)
As the file complies with the OCI standards, the universal `Containerfile` name should be used.

In addition to this, since the commands are combined into a single step, any changes require almost a full rebuild of the image. This is undesirable, so I broke up the single RUN step into multiple.

### Bundle python not via features

As new tooling for `devcontainers` emerges, features should not be relied on for core functionality.
This is a requirement for the next change. 

### Bundle PlatformIO Core in the image

Since python is available from the image, we can bundle PlatformIO Core in the container.
This is desirable when prebuilding, since the user won't have to install PlatformIO Core on the first run, and reload the window.
This also allows `pio` to be included in `$PATH`, further improving the usability of the image.

### Fedora Compatibility

I'm a Fedora user, and I found a bug where `/dev/ttyACM*` is owned by GID `18`, instead of Debian's `20`.
I solved this by creating an additional group with the GID 18 and adding the user to it.

Furthermore, I also added an explanation about the different base image variants, a warning for debian 10 and ubuntu as I did not test that.

### CODE REVIEW

**Comment by FlyinPancake** [comment]
> [!NOTE]
> I've seen #6 but that was a workaround, and this reverts that, but fixes it as well

**Comment by prenone** [comment]
Hello @FlyinPancake!
I am really happy that so many people are finding this repository useful and are contributing.
I will run some tests in the next couple of days, both with my machine and some others (as much as I can gather lol).
The commit looks great and I will be more than happy to merge if the tests are successful. In the mean time, if anyone is reading this and has the ability to test on their machine, please leave a comment here.
Again, many thanks for the contribution

**Comment by FlyinPancake** [comment]
Well I just got a new (to me) PC so I'll be able to test on 2 of my machines

**Comment by prenone** [comment]
I did the appropiate tests on my machine and everything works fine!
Thank you very much for contributing and have a great day :)

**Pull request merged**
